spring.application.name=hashing

spring.datasource.url=jdbc:postgresql://localhost:5432/pancardstorage
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:dks@1213}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

pan.pepper=${PAN_PEPPER:D3xFPN14N5rkewqfWdbG4OdY}

jwt.secret=${JWT_SECRET:9f4b2c8e1a7d3f6b0e5c9a2d8b7e4f1c3a6d9b2e5c8f1a4d7b0e3c6f9a2d5b8}

server.port=8080